// Public API of es-core. See README.md.
export type * from "./types.js";
export { extractPart, parseMessage } from "./parse.js";
export { serializeMessage, serializeReceipt, replyTargetOf } from "./serialize.js";
export { threadMessages } from "./threading/thread.js";
export { groupByParticipants } from "./chats.js";
export { carrierSubject, subjectNoteOf, topicsOf } from "./topics.js";
export { classifyMessage } from "./classify.js";
export { isInterleaved, splitQuoted, unquote, unquotedLines } from "./quotes.js";
export { collapse } from "./util/text.js";
export { quoteForReply } from "./reply-quote.js";
export { quotedFragmentOf, replyCardOf } from "./reply-card.js";
export type { ReplyCardOptions } from "./reply-card.js";
export type { QuoteOptions } from "./reply-quote.js";
export type { GroupOptions } from "./chats.js";
export { normalizeSubject, subjectKey } from "./threading/subject.js";
export type { NormalizedSubject } from "./threading/subject.js";
export { deriveContacts } from "./contacts.js";
export type { DeriveContactsOptions } from "./contacts.js";
export { canonicalAddress } from "./headers/canonical.js";
export { deriveDid, formatDid, parseDid, isValidDid } from "./did.js";
export type { EsDid } from "./did.js";
export { ES_MEDIA_TYPE, ES_DRAFT_MEDIA_TYPE, ES_TEXT_MAX_BYTES } from "./es/schema.js";
